# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homes
    pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume.git'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SwiftyUserDefaults'
    pod 'SVProgressHUD'
    pod 'ImagePicker'
	pod 'GoogleSignIn'
    pod 'TagListView'
end
